<?php

use Drupal\Core\Url;

/**
 * Implements hook_entity_type_build().
 */
function quick_node_clone_entity_type_build(array &$entity_types) {
  if(isset($entity_types['node'])) {
    $entity_types['node']->setFormClass('quick_node_clone', 'Drupal\quick_node_clone\Form\QuickNodeCloneNodeForm');
  }

}

/**
 * Implements hook_entity_operation().
 */
function quick_node_clone_entity_operation(\Drupal\Core\Entity\EntityInterface $entity) {
  $operations = [];

  if (
    \Drupal::currentUser()->hasPermission('access content overview') &&
    \Drupal::routeMatch()->getRouteName() === 'system.admin_content'
  ) {
    $path = '/clone/' . $entity->id() . '/quick_clone';
    $operations['quick_clone'] = [
      'title' => t('Clone'),
      'weight' => '100',
      'url' => Url::fromUri('internal:/' . trim($path, '/')),
    ];
  }

  return $operations;
}
